version: "3"
services:
  app:
    build: ./docker/app
    volumes:
      - ../:/workspace:cached
    ports:
      - 80:80
    tty: true
    environment:
      APP_ENV: local
      PHP_EXTENSION_XDEBUG: 1
      PHP_EXTENSION_PGSQL: 1
      PHP_EXTENSION_PDO_PGSQL: 1
      PHP_EXTENSION_GD: 1
      APACHE_DOCUMENT_ROOT: /workspace/docroot
    networks:
      - front
  db:
    image: percona:5.7.22
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: d9
      MYSQL_USER: d9
      MYSQL_PASSWORD: d9
      MYSQL_ROOT_PASSWORD: d9root
    networks:
      - front
  adminer:
    image: adminer:standalone
    restart: unless-stopped
    ports:
      - 8082:8080
    links:
      - db:db
    depends_on:
      - db
    networks:
      - front
  solr:
    image: solr:7-slim
    restart: unless-stopped
    ports:
      - 8983:8983
    volumes:
      - ./docker/solr-conf/7.x:/solr-conf/conf
    entrypoint:
      - bash
      - "-c"
      - "precreate-core default /solr-conf; exec solr -f"
    depends_on:
      - app
      - db
    networks:
      - front
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
networks:
  front:
    driver: bridge
